
---
- hosts: all
  gather_facts: no
  tasks:
    - name: Run command with ERROR in stderr
      command: ls /non_existing_path 2>&1 | sed s/ERROR/REPLACE_ERROR/g >&2
      register: result
      ignore_errors: yes

    - name: Display result
      debug: var=result

    - name: Set fact to logically true
      set_fact:
        logically_true: "{{ true or false }}"

    - name: Print logically true fact
      debug:
        msg: "Logically true fact is {{ logically_true }}"

    - name: Raise an exception
      debug:
        msg: "This shouldn't happen"
        failed_when: true

    - name: Generate a segfault
      command: ln -s /non_existing_path /var/tmp/`python -c 'print "A"*100000'` 
