
- name: Trigger Python error on Jinja2
  hosts: all
  gather_facts: no
  tasks:
    - name: Set invalid variable
      set_fact:
        invalid_var: "{{ invalid_dict['invalid_key'] }}"

    # this will raise a Jinja2 error as invalid_dict is not defined
