
---
- name: Playbook to Handle Errors with Rescue Blocks
  hosts: all
  tasks:
    - name: Task 1
      debug:
        msg: "This is Task 1"

    - name: Task 2
      debug:
        msg: "This is Task 2"

    - name: Task 3 with rescue block
      block:
        - name: Subtask 1
          debug:
            msg: "This is Subtask 1"

        - name: Subtask 2
          command: /usr/bin/invalidcommand
          register: cmdoutput
          ignore_errors: true

      rescue:
        - name: Rescue
          debug:
            msg: "An error occurred! Skipping to the next task"
          
    - name: Task 4
      debug:
        msg: "This is Task 4"
  
