
---
- name: GCP Compute Instance Facts Google Auth Error
  hosts: all
  gather_facts: no
  vars:
    project_id: YOUR_PROJECT_ID_HERE
  tasks:
    - name: Verify Google Auth Module
      block:
        - name: Test Google Auth Module
          gcp_auth:
            credentials_file: "{{ GOOGLE_APPLICATION_CREDENTIALS }}"
      rescue:
        - name: Gather Google Auth Debug Info
          debug:
            msg: "{{ ansible_failed_result }}"
        - name: Fail Task
          fail:
            msg: "Google Auth Module Test Failed"

    - name: Gather GCP Compute Instance Facts
      block:
        - name: Test GCP Compute Instance Facts Module
          gcp_compute_instance_facts:
            project: "{{ project_id }}"
            auth_kind: "{{ auth_kind }}"
        - name: Debug GCP Compute Instance Facts Module Results
          debug:
            var: gcp_compute_instance_facts
      rescue:
        - name: Gather GCP Compute Instance Facts Debug Info
          debug:
            msg: "{{ ansible_failed_result }}"
        - name: Fail Task
          fail:
            msg: "GCP Compute Instance Facts Module Test Failed"
