
- name: Test error handling
  hosts: all
  tasks:
  - name: Execute command that throws an error
    shell: "<command that throws an error>"
    register: cmd_output
    ignore_errors: true
  - name: Display error message if it exists
    debug:
      msg: "Error message: {{ cmd_output.stderr }}"
  - name: Fail if command failed
    fail:
      msg: "Command failed with RC={{ cmd_output.rc }}"
    when: cmd_output.rc != 0
